### ISSUE TITLE
Make social icons section drop down beneath title on small screens

### ISSUE THREAD

**Issue by tetov** [ribice/kiss#62]
I've been trying to figure out how to change the partial nav.html to make the social icon jump down a line when the screen is smaller. On smaller screens the social icons hides the title. I don't know enough CSS (and I don't understand the style.css enough, is it taken from a particular framework?).

![www ribice ba_ iphone 5_se](https://user-images.githubusercontent.com/14882117/51807182-02d43580-2284-11e9-8cbb-9e8f527faebc.png)

**Comment by ribice** [comment]
Will look into this.

**Comment by ribice** [comment]
Resolved via #77

**Comment by pointfourone** [comment]
@ribice the pull request #77 makes the social icon display a bit weird on my mobile device.

It looks like this on commit a752be3
![a752be3](https://user-images.githubusercontent.com/47925053/67249646-06e55a80-f486-11e9-9a1d-89cdb0bfe857.png)

and like this on commit 9c5638b
![9c5638b](https://user-images.githubusercontent.com/47925053/67249652-0cdb3b80-f486-11e9-9dc6-16330c9bd643.png)

What do you think? Is it possible to shift `.nav-right` below `.nav-left` only when they begin to overlap rather than imposing a [minimum width of 767px](https://github.com/ribice/kiss/commit/9c5638bbf3071f216bef76a5c81660d59cce431c#diff-a16a51aaea7dc21d3202074fc7228024R5270)? Besides, what if someone uses a custom section below the left and right nav bars as mentioned [here](https://github.com/ribice/kiss#add-sections)? It would make things messy I guess.

**Comment by bashovski** [comment]
Will be resolved as soon as possible.

**Comment by ribice** [comment]
@pointfourone How is it after #78?

**Comment by pointfourone** [comment]
@ribice @bashovski works as expected for now. Thanks!
